# Deployment sample config
services:
  postgres:
    image: postgres:18-alpine
    container_name: crossbill-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: crossbill
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-crossbill_secure_password}
      POSTGRES_DB: crossbill
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U crossbill"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
    networks:
      - crossbill-network

  app:
    image: tumetsu/crossbill:latest
    container_name: crossbill-app
    restart: unless-stopped
    pull_policy: always
    ports:
      - "8000:8000"
    environment:
      # Refer to all possible environment variables in /backend/.env.example
      DATABASE_URL: postgresql://crossbill:${POSTGRES_PASSWORD:-crossbill_secure_password}@postgres:5432/crossbill
      ENVIRONMENT: production
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CORS_ORIGINS: '["https://yourdomain.com"]'
      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRE_MINUTES: 15
      REFRESH_TOKEN_EXPIRE_DAYS: 30
      REFRESH_TOKEN_SECRET_KEY: ${REFRESH_TOKEN_SECRET_KEY}
      COOKIE_SECURE: true
      ALLOW_USER_REGISTRATIONS: false
      PORT: 8000
    volumes:
      - type: bind
        source: /path/on/host/for/crossbill/book-files
        target: /app/book-files
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - crossbill-network

volumes:
  postgres_data:
    driver: local

networks:
  crossbill-network:
    driver: bridge
